//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.resources.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Software.resources.i18n.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bing 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Bing {
            get {
                return ResourceManager.GetString("MainWindow_Button_Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A search engine 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Bing_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Bing_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenshinMap 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinMap {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the map interface 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinMap_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinMap_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenshinRole 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinRole {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the Genshin Impact character interface 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinRole_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinRole_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Home {
            get {
                return ResourceManager.GetString("MainWindow_Button_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return to the homepage 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Home_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Home_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HonkaiImpact3 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_HonkaiImpact3 {
            get {
                return ResourceManager.GetString("MainWindow_Button_HonkaiImpact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the character interface in Honkai Impact 3rd 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_HonkaiImpact3_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_HonkaiImpact3_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MoveChest 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_MoveChest {
            get {
                return ResourceManager.GetString("MainWindow_Button_MoveChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start pushing the boxes 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_MoveChest_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_MoveChest_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlayGames 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_PlayGames {
            get {
                return ResourceManager.GetString("MainWindow_Button_PlayGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch the game 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_PlayGames_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_PlayGames_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectUP 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_SelectUP {
            get {
                return ResourceManager.GetString("MainWindow_Button_SelectUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the query interface 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_SelectUP_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_SelectUP_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up some functions 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Settings_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Settings_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarRail 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StarRail {
            get {
                return ResourceManager.GetString("MainWindow_Button_StarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the character interface in Honkai: Star Rail 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StarRail_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_StarRail_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StreePortal 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StreePortal {
            get {
                return ResourceManager.GetString("MainWindow_Button_StreePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the StreetPortal website 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StreePortal_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_StreePortal_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updata 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Updata {
            get {
                return ResourceManager.GetString("MainWindow_Button_Updata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Literal meaning 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Updata_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Updata_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Version {
            get {
                return ResourceManager.GetString("MainWindow_Button_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the interface for historical version update content 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Version_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Version_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now it&apos;s all approximate 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_Ts {
            get {
                return ResourceManager.GetString("MainWindow_Label_Ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Json 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_BuildJson {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_BuildJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_City_Address {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_City_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the folder 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Delete_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Delete_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the Logs folder 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Delete_Logs_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Delete_Logs_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the Log folder 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Open_Log_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Open_Log_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open log panel 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Open_LogDashboard {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Open_LogDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the Logs folder 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Open_Logs_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Open_Logs_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the Music folder 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Open_Music_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Open_Music_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the Resources folder 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Open_Resources_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Open_Resources_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the software root directory 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Open_Root_Directory_Folder {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Open_Root_Directory_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot Software 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Reboot_Software {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Reboot_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot Software(Administrator) 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Click_Root_Reboot_Software {
            get {
                return ResourceManager.GetString("PageSettings_Button_Click_Root_Reboot_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Luanguage_en_US {
            get {
                return ResourceManager.GetString("PageSettings_Button_Luanguage_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_Luanguage_zh_CN {
            get {
                return ResourceManager.GetString("PageSettings_Button_Luanguage_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test network connection 的本地化字符串。
        /// </summary>
        public static string PageSettings_Button_TestNetworkConnection {
            get {
                return ResourceManager.GetString("PageSettings_Button_TestNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_About {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color settings 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_ColorSettings {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_ColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File operation 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_FileOperation {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_FileOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden switch 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_HiddenSwitch {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_HiddenSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch settings 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_LaunchSettings {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_LaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network connection test 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_NetworkTest {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_NetworkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path settings 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_PathSettings {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_PathSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software operation 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_SoftwareOperation {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_SoftwareOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update address 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_UpdateAddress {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_UpdateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weather address 的本地化字符串。
        /// </summary>
        public static string PageSettings_GroupBox_WeatherAddress {
            get {
                return ResourceManager.GetString("PageSettings_GroupBox_WeatherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter address information: 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_CityAddress {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_CityAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in the structured address information: Province + City + District + Town + Village + Street + House Number. Fill in according to the requirements 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_CityAddress_Tip {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_CityAddress_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic update 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_EnableAutoUpdateCheckBox {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_EnableAutoUpdateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start counting 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_EnableCountingCheckBox {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_EnableCountingCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game launch path： 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_GamePath {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New software update address： 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_New_Update_IP_address_TextChanged {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_New_Update_IP_address_TextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target address 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_TargetAddress {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_TargetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software update address： 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_Update_IP_address_TextChanged {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_Update_IP_address_TextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log update address： 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_Update_Log_IP_address_TextChanged {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_Update_Log_IP_address_TextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateTimeColor： 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_UpdateTimeColor {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_UpdateTimeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VersionColor： 的本地化字符串。
        /// </summary>
        public static string PageSettings_TextBlock_VersionColor {
            get {
                return ResourceManager.GetString("PageSettings_TextBlock_VersionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string PageSettings_ToggleSwitch_OffContent_Default {
            get {
                return ResourceManager.GetString("PageSettings_ToggleSwitch_OffContent_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        public static string PageSettings_ToggleSwitch_OnContent_Default {
            get {
                return ResourceManager.GetString("PageSettings_ToggleSwitch_OnContent_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string System_MainWindow_Button_About {
            get {
                return ResourceManager.GetString("System_MainWindow_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do&apos;t Click 的本地化字符串。
        /// </summary>
        public static string System_MainWindow_Button_DoNotClick {
            get {
                return ResourceManager.GetString("System_MainWindow_Button_DoNotClick", resourceCulture);
            }
        }
    }
}
