//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.resources.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Software.resources.i18n.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bing 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Bing {
            get {
                return ResourceManager.GetString("MainWindow_Button_Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Bing_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Bing_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenshinMap 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinMap {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinMap_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinMap_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenshinRole 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinRole {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_GenshinRole_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_GenshinRole_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Home {
            get {
                return ResourceManager.GetString("MainWindow_Button_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Home_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Home_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HonkaiImpact3 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_HonkaiImpact3 {
            get {
                return ResourceManager.GetString("MainWindow_Button_HonkaiImpact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_HonkaiImpact3_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_HonkaiImpact3_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MoveChest 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_MoveChest {
            get {
                return ResourceManager.GetString("MainWindow_Button_MoveChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_MoveChest_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_MoveChest_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlayGames 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_PlayGames {
            get {
                return ResourceManager.GetString("MainWindow_Button_PlayGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_PlayGames_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_PlayGames_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectUP 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_SelectUP {
            get {
                return ResourceManager.GetString("MainWindow_Button_SelectUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_SelectUP_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_SelectUP_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up some functions 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Settings_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Settings_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarRail 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StarRail {
            get {
                return ResourceManager.GetString("MainWindow_Button_StarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StarRail_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_StarRail_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StreePortal 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StreePortal {
            get {
                return ResourceManager.GetString("MainWindow_Button_StreePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_StreePortal_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_StreePortal_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updata 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Updata {
            get {
                return ResourceManager.GetString("MainWindow_Button_Updata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Updata_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Updata_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Version {
            get {
                return ResourceManager.GetString("MainWindow_Button_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Version_Tip {
            get {
                return ResourceManager.GetString("MainWindow_Button_Version_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now it&apos;s all approximate 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_Ts {
            get {
                return ResourceManager.GetString("MainWindow_Label_Ts", resourceCulture);
            }
        }
    }
}
